version: '3.8'

services:
  etl_pipeline:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sales-data-etl
    container_name: sales_data_etl_pipeline
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.py:/app/config.py
      - ./.env:/app/.env  # Mount .env file
    environment:
      - PYTHONPATH=/app
      - ENV=development
    depends_on:
      - database
    
  database:
    image: postgres:13
    container_name: sales_data_postgres
    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Optional: Add adminer for database management
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:

networks:
  default:
    name: sales-etl-network
